name = "lightning-flashcard"
main = "src/index.js"
compatibility_date = "2023-12-01"

# 自訂網域路由
[[routes]]
pattern = "cards.finrod.xyz/*"
zone_name = "finrod.xyz"

[[d1_databases]]
binding = "DB"
database_name = "flashcard-db"
database_id = "de99d202-0020-4b65-b062-2654d6643de6"

# 本地開發數據庫 (僅用於開發環境)
# [[d1_databases]]
# binding = "DB_LOCAL"
# database_name = "flashcard-db-local"
# database_id = "local-development-db"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "CACHE"
id = "a63079ba1e6447919d5ff3e0616af2aa"
preview_id = "089d46ef9ef64e59961c0719efa8e2ba"